### ISSUE TITLE
Font cannot be viewed or installed on Windows 10 v2004 (build 20221)

### ISSUE THREAD

**Issue by anaisbetts** [unicode-org/last-resort-font#1]
```
---------------------------
Windows Font Viewer 
---------------------------
The requested file LastResort-Regular.ttf is not a valid font file. 
---------------------------
OK   
---------------------------
```

**Comment by PeterConstable** [comment]
This is not a font issue: Windows doesn't support cmap subtable format 13, which means it doesn't support last-resort fonts. This should be reported to Microsoft using the Feedback Hub app in Windows 10.

**Comment by babelstone** [comment]
I think that this issue was closed prematurely. As discussed on the [unicode-org](https://unicode-org.slack.com/archives/C01C9HA8UAF) Slack channel, it is a font issue that the font does not install on Windows, and there are some Windows applications (including latest versions of Word) which do support Format 13 fonts when installed on windows. This is a screenshot of Word (Office 2019) correctly displaying glyphs from a tweaked version of the Format 13 Last Resort font (which installs OK on Windows 2000 through Windows 10).
![Word_LastResort](https://user-images.githubusercontent.com/20558386/96013343-0d11db00-0e3d-11eb-8ccf-ef3a5da6b58d.png)

**Comment by PathogenDavid** [comment]
While some Windows tools (including font viewer) can't render the font, I was able to install it on Windows 10 20H2 without issue. Font viewer opens fine despite being unable to render it:

![image](https://user-images.githubusercontent.com/278957/99717090-891bc600-2a6e-11eb-8365-d0d08155be82.png)
