### ISSUE TITLE
Version font files in releases or include in archive

### ISSUE THREAD

**Issue by BrianInglis** [unicode-org/last-resort-font#13]
Nice prompt update, but it would be nice to have the font files included in the versioned archive, or have individually versioned font files in the releases, so that processes that depend on version changes will download the updated font files, rather than using the previously cached files, which turned out to be `15.000`, after packaging and installing! ;^>

**Comment by kenlunde** [comment]
Have you tried using `https://github.com/unicode-org/last-resort-font/releases/latest/download/LastResort-Regular.ttf`? This iis far from the only open source font repository that provides the installable font resources as assets in a release.

**Comment by BrianInglis** [comment]
That is also not a *versioned* file name, so the (*dumb*) package builder download thinks it has already downloaded the cached source file(s). 
We are considering how we could smarten up the package builder download cache with minimal overhead to avoid redoing already cached downloads to check metadata. 
For other processes, we are using `curl -I` to to check headers with crafted URIs to see if certain git operations are remotely supported. 
Perhaps we may be able to use that technique with *non-versioned* (would not containing any digit strings be an adequate criterion?) file names only to check size and possibly also modified date.

**Comment by alerque** [comment]
You can easily make the URL versioned by linking to the right tag:

```
https://github.com/unicode-org/last-resort-font/releases/download/15.100/LastResort-Regular.ttf
```

**Comment by kenlunde** [comment]
Based on the above, it sounds like that this issue can be safely closed.

**Comment by BrianInglis** [comment]
I realize the non-`latest` *URIs* are versioned but the downloadable font *files* are NOT versioned and are NOT included within the versioned downloadable archives preferred by distro packagers, unlike most other font packages. 
I am a font hog and know how frustrating it can be to check downloads to see if the latest found is actually a later revision of the font contents. 
I will see if I can check versions with exiftool, X and other font utilities, to come up with standard shell and utility commands, which may modify download preprocessing to validate downloaded versions, clear from the download cache, then redrive the package source downloads, over and above the `curl` generic *GH* non-versioned file name size and date checks mentioned above.

**Comment by alerque** [comment]
> unlike most other font packages.

Most font packages do this wrong by storing generated font binaries in VCS. Those that do it right may have a versioned *release* package (not the `git archive` generated source package) with font binaries, but in that case the de facto correct way to do that is to have the wrapper archive (zip/etc) have a version name but *not the extracted font files*. Those are typically, and in my view correctly, still not identified with a version in their name.

An alternative with the version in the filename does make sense if you have a build system that only looks at filenames for dependencies. That *could* be done by attaching a renamed copy to the release, but it can also be done by most download tooling at download time. Since you need the tag version to get the URL right anyway just set the output filename yourself on download.
