### ISSUE TITLE
ETA of source files and build scripts?

### ISSUE THREAD

**Issue by clin1234** [unicode-org/last-resort-font#7]
Are the glyphs of the Last Resort Font modifiable in Font Forge?

**Comment by rickmcgowan** [comment]
While there is no ETA for providing the source files and build scripts, if time and resources permit, they may become available later this at the same time that the project is updated to reflect Unicode Version 15.0. Keep in mind that this is an entirely volunteer project with no commitments.

As to whether the glyphs are modifiable in FontForge, sure, because they are outlines in a known format, but the real question is whether FontForge is able to export both flavors of the font, and the answer would be a very confident no.
